# Generated by Django 6.0.6 on 2026-09-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tratamientos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=20)),
                ('apellido_paciente', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio', models.CharField(blank=True, max_length=50)),
                ('localidad', models.CharField(blank=True, max_length=50)),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('obra_social', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('descripcion', models.TextField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.profesional')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='pacientes.historiaclinica')),
            ],
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('asignado', 'Asignado'), ('finalizado', 'Finalizado'), ('ausente', 'Ausente'), ('cancelado', 'Cancelado')], default='asignado', max_length=20)),
                ('fecha_asistencia', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tratamientos.tratamiento')),
            ],
        ),
    ]
