# Generated by Django 6.0.6 on 2026-07-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombrePaciente', models.CharField(max_length=20)),
                ('apellidoPaciente', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField()),
                ('domicilio', models.CharField(blank=True, max_length=50)),
                ('localidad', models.CharField(blank=True, max_length=50)),
                ('correoElectronico', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('obraSocial', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(blank=True, max_length=1)),
            ],
        ),
    ]
