# Generated by Django 6.0.6 on 2026-08-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='apellidoPaciente',
            new_name='apellido_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='correoElectronico',
            new_name='correo_electronico',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombrePaciente',
            new_name='nombre_paciente',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='obraSocial',
            new_name='obra_social',
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField()),
                ('descripcion', models.TextField()),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.profesional')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='pacientes.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('asignado', 'Asignado'), ('finalizado', 'Finalizado'), ('ausente', 'Ausente')], default='asignado', max_length=20)),
                ('fecha_asistencia', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
        ),
    ]
