# Generated by Django 6.0.6 on 2026-08-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_rename_apellidopaciente_paciente_apellido_paciente_and_more'),
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tratamientos.tratamiento'),
        ),
    ]
