# Generated by Django 6.0.6 on 2026-09-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_turno_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('asignado', 'Asignado'), ('finalizado', 'Finalizado'), ('ausente', 'Ausente'), ('cancelado', 'Cancelado')], default='asignado', max_length=20),
        ),
    ]
