# Generated by Django 6.0.6 on 2026-09-20 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_turno_estado'),
        ('usuarios', '0004_movimientocaja_categoria_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('privada', 'Privada'), ('tratamiento', 'Tratamiento'), ('consulta', 'Consulta'), ('evaluacion', 'Evaluación'), ('ntf', 'NTF'), ('prp', 'PRP')], default='privada', max_length=20)),
                ('fecha_evolucion', models.DateField()),
                ('numero_sesion', models.PositiveIntegerField(blank=True, null=True)),
                ('resumen', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evoluciones/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evoluciones', to='pacientes.historiaclinica')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evoluciones', to='usuarios.profesional')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evoluciones', to='pacientes.turno')),
            ],
        ),
    ]
