# Generated by Django 6.0.6 on 2026-09-20 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_sexo_evolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='historia_clinica', to='pacientes.paciente'),
        ),
    ]
