# Generated by Django 6.0.6 on 2026-09-20 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_historiaclinica_paciente'),
        ('usuarios', '0004_movimientocaja_categoria_movimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evoluciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evoluciones', to='usuarios.profesional'),
        ),
        migrations.AlterField(
            model_name='evolucion',
            name='tipo',
            field=models.CharField(choices=[('control_mtc', 'Control MTC'), ('control_ntf', 'Control NTF'), ('control_prp', 'Control PRP'), ('mtc', 'MTC'), ('ntf', 'NTF'), ('nueva_evaluacion', 'Nueva evaluación'), ('primera_consulta', 'Primera consulta'), ('privada', 'Privada'), ('prp', 'PRP')], default='privada', max_length=20),
        ),
    ]
