# Generated by Django 6.0.6 on 2026-09-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_evolucion_usuario_alter_evolucion_profesional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolucion',
            name='resumen',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
