# Generated by Django 6.0.6 on 2026-09-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_alter_evolucion_resumen'),
        ('tratamientos', '0005_remove_planpago_nombre_tratamiento_planpago_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tratamientos.planpago'),
        ),
    ]
