# Generated by Django 6.0.6 on 2026-10-06 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_turno_plan'),
        ('tratamientos', '0005_remove_planpago_nombre_tratamiento_planpago_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='tratamiento_indicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evoluciones_indicacion', to='tratamientos.tratamiento'),
        ),
    ]