# Generated by Django 6.0.6 on 2026-10-06 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_evolucion_tratamiento_indicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='indicacion_medica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos_indicados', to='pacientes.evolucion'),
        ),
        migrations.AddField(
            model_name='turno',
            name='nota',
            field=models.TextField(blank=True),
        ),
    ]
