# Generated by Django 6.0.6 on 2026-10-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_notaagenda_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaagenda',
            name='fecha',
            field=models.DateField(),
        ),
    ]
