# Generated by Django 6.0.6 on 2026-09-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('numero_receta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_receta', models.DateField(auto_now_add=True)),
                ('dosis', models.SmallIntegerField()),
                ('frecuencia', models.CharField(blank=True, max_length=20)),
                ('duracion_indicacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.IntegerField(primary_key=True, serialize=False)),
                ('duracion_sesion', models.DurationField()),
                ('numero_sesion', models.SmallIntegerField()),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('abonado', 'Abonado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tratamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion_tratamiento', models.DurationField()),
                ('sesion_tratamiento', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('valor_sesion', models.IntegerField()),
                ('fecha_inicio_tratamiento', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercadopago', 'MercadoPago'), ('tarjeta_debito', 'Tarjeta Debito'), ('tarjeta_credito', 'Tarjeta Credito')], default='efectivo', max_length=20, verbose_name='Metodo de pago')),
                ('nombre_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tratamientos.tratamiento')),
            ],
        ),
    ]
