# Generated by Django 6.0.6 on 2026-08-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_rename_apellidopaciente_paciente_apellido_paciente_and_more'),
        ('productos', '0002_archivo'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('duracion_tratamiento', models.DurationField()),
                ('sesion_tratamiento', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('valor_sesion', models.IntegerField()),
                ('fecha_inicio_tratamiento', models.DateField()),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('numero_receta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_receta', models.DateField(auto_now_add=True)),
                ('dosis', models.SmallIntegerField()),
                ('frecuencia', models.CharField(blank=True, max_length=20)),
                ('duracion_indicacion', models.CharField(max_length=20)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
                ('id_historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.historiaclinica')),
                ('id_profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.IntegerField(primary_key=True, serialize=False)),
                ('duracion_sesion', models.DurationField()),
                ('numero_sesion', models.SmallIntegerField()),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('abonado', 'Abonado')], default='pendiente', max_length=20)),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones', to='tratamientos.planpago')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.turno')),
            ],
        ),
    ]
