# Generated by Django 6.0.6 on 2026-09-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='precio_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='requiere_plan',
            field=models.BooleanField(default=False),
        ),
    ]
