# Generated by Django 6.0.6 on 2026-09-24 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_alter_evolucion_resumen'),
        ('tratamientos', '0004_cargar_tratamientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planpago',
            name='nombre_tratamiento',
        ),
        migrations.AddField(
            model_name='planpago',
            name='dni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planpago',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='planpago',
            name='sesiones_consumidas',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planpago',
            name='sesiones_total',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planpago',
            name='tratamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tratamientos.tratamiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planpago',
            name='fecha_inicio_tratamiento',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='planpago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mercadopago', 'MercadoPago'), ('tarjeta_debito', 'Tarjeta Debito'), ('tarjeta_credito', 'Tarjeta Credito')], default='efectivo', max_length=20),
        ),
    ]
