# Generated by Django 6.0.6 on 2026-10-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0005_remove_planpago_nombre_tratamiento_planpago_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='agenda_categoria',
            field=models.CharField(choices=[('consultorio', 'Prestaciones del consultorio'), ('mtc', 'MTC'), ('ntf', 'NTF'), ('prp', 'PRP')], default='consultorio', max_length=20),
        ),
    ]
