<<<<<<< HEAD
# Generated by Django 6.0.6 on 2026-08-04 00:43

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 6.0.6 on 2026-08-04 19:23

>>>>>>> feature/models-tratamientos
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> feature/models-tratamientos
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_caja', models.IntegerField(default=0)),
                ('apertura_caja', models.DateField(auto_now_add=True)),
                ('cierre_caja', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20)),
                ('importe_movimiento', models.IntegerField()),
                ('fecha_movimiento', models.DateField(auto_now_add=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.caja')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
            name='PlanPago',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('valor_sesion', models.IntegerField()),
                ('fecha_inicio_tratamiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('numero_receta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_receta', models.DateField(auto_now_add=True)),
                ('dosis', models.SmallIntegerField()),
                ('frecuencia', models.CharField(blank=True, max_length=20)),
                ('duracion_indicacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.IntegerField(primary_key=True, serialize=False)),
                ('duracion_sesion', models.DurationField()),
                ('numero_sesion', models.SmallIntegerField()),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('abonado', 'Abonado')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('duracion_tratamiento', models.DurationField()),
                ('sesion_tratamiento', models.SmallIntegerField(default=1)),
>>>>>>> feature/models-tratamientos
            ],
        ),
    ]
