# Generated by Django 6.0.6 on 2026-09-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='apertura_caja',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='cierre_caja',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
