# Generated by Django 6.0.6 on 2026-09-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_caja_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='categoria_movimiento',
            field=models.CharField(choices=[('venta', 'Venta'), ('pago_proveedor', 'Pago a Proveedor'), ('pago_servicio', 'Pago de Servicio'), ('pago_impuesto', 'Pago de impuesto'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='descripcion_movimiento',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
