# Generated by Django 6.0.6 on 2026-10-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_grupos_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Usuario', models.CharField(max_length=100)),
                ('apellido_Usuario', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=128)),
                ('rol_Usuario', models.CharField(choices=[('admin', 'Admin'), ('empleado', 'Empleado'), ('cliente', 'Cliente')], default='empleado', max_length=20)),
            ],
        ),
    ]
