# Generated by Django 6.0.6 on 2026-08-04 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=20)),
                ('cantidad_producto', models.SmallIntegerField(default=0)),
                ('categoria_producto', models.CharField(max_length=20)),
                ('precio_producto', models.IntegerField()),
                ('stock_minimo', models.SmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=20)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.IntegerField()),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unitaria', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='productos.venta')),
            ],
        ),
    ]
