# Generated by Django 6.0.6 on 2026-08-23 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_rename_apellidopaciente_paciente_apellido_paciente_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_adjunto', models.FileField(upload_to='evaluaciones/')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='pacientes.evaluacionmedica')),
            ],
        ),
    ]
